"""flok dashboard init

Revision ID: 0950a8e2a825
Revises: 
Create Date: 2021-06-17 02:48:34.549308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0950a8e2a825'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_table('destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_maps_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_destinations')),
    sa.UniqueConstraint('google_maps_id', name=op.f('uq_destinations_google_maps_id'))
    )
    op.create_table('flight_trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('travel_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flight_trips'))
    )
    op.create_table('lodging_partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lodging_partners'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('companies_admins',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], name=op.f('fk_companies_admins_admin_id_users')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_companies_admins_company_id_companies')),
    sa.PrimaryKeyConstraint('admin_id', 'company_id', name=op.f('pk_companies_admins'))
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('preferred_airport', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_employees_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees'))
    )
    op.create_table('flight_legs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_trip_id', sa.Integer(), nullable=False),
    sa.Column('leg_order', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.String(), nullable=False),
    sa.Column('from_airport', sa.String(), nullable=False),
    sa.Column('to_airport', sa.String(), nullable=False),
    sa.Column('departure_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrival_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('flight_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flight_trip_id'], ['flight_trips.id'], name=op.f('fk_flight_legs_flight_trip_id_flight_trips')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flight_legs'))
    )
    op.create_table('lodging_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lodging_partner_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('proposal_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], name=op.f('fk_lodging_proposals_destination_id_destinations')),
    sa.ForeignKeyConstraint(['lodging_partner_id'], ['lodging_partners.id'], name=op.f('fk_lodging_proposals_lodging_partner_id_lodging_partners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lodging_proposals'))
    )
    op.create_table('retreats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_retreats_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retreats'))
    )
    op.create_table('users_login_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_login_ids_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_login_ids')),
    sa.UniqueConstraint('login_id', name=op.f('uq_users_login_ids_login_id'))
    )
    op.create_table('users_login_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('unique_id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_login_providers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_login_providers'))
    )
    op.create_table('users_login_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login_token', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_login_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_login_tokens')),
    sa.UniqueConstraint('login_token', name=op.f('uq_users_login_tokens_login_token'))
    )
    op.create_table('employees_to_flight_trips',
    sa.Column('arrival_flight_trip_id', sa.Integer(), nullable=False),
    sa.Column('departure_flight_trip_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('retreat_id', sa.Integer(), nullable=False),
    sa.Column('est_cost', sa.Integer(), nullable=False),
    sa.Column('final_cost', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['arrival_flight_trip_id'], ['flight_trips.id'], name=op.f('fk_employees_to_flight_trips_arrival_flight_trip_id_flight_trips')),
    sa.ForeignKeyConstraint(['departure_flight_trip_id'], ['flight_trips.id'], name=op.f('fk_employees_to_flight_trips_departure_flight_trip_id_flight_trips')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employees_to_flight_trips_employee_id_employees')),
    sa.ForeignKeyConstraint(['retreat_id'], ['retreats.id'], name=op.f('fk_employees_to_flight_trips_retreat_id_retreats')),
    sa.PrimaryKeyConstraint('employee_id', 'retreat_id', name=op.f('pk_employees_to_flight_trips'))
    )
    op.create_table('lodging_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('retreat_id', sa.Integer(), nullable=False),
    sa.Column('lodging_partner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lodging_partner_id'], ['lodging_partners.id'], name=op.f('fk_lodging_contracts_lodging_partner_id_lodging_partners')),
    sa.ForeignKeyConstraint(['retreat_id'], ['retreats.id'], name=op.f('fk_lodging_contracts_retreat_id_retreats')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lodging_contracts'))
    )
    op.create_table('lodging_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('retreat_id', sa.Integer(), nullable=False),
    sa.Column('num_employees', sa.Integer(), nullable=False),
    sa.Column('dates', sa.JSON(), nullable=False),
    sa.Column('meeting_space', sa.JSON(), nullable=False),
    sa.Column('rooming_preferences', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['retreat_id'], ['retreats.id'], name=op.f('fk_lodging_preferences_retreat_id_retreats')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lodging_preferences'))
    )
    op.create_table('selected_destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('retreat_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], name=op.f('fk_selected_destinations_destination_id_destinations')),
    sa.ForeignKeyConstraint(['retreat_id'], ['retreats.id'], name=op.f('fk_selected_destinations_retreat_id_retreats')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_selected_destinations'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('selected_destinations')
    op.drop_table('lodging_preferences')
    op.drop_table('lodging_contracts')
    op.drop_table('employees_to_flight_trips')
    op.drop_table('users_login_tokens')
    op.drop_table('users_login_providers')
    op.drop_table('users_login_ids')
    op.drop_table('retreats')
    op.drop_table('lodging_proposals')
    op.drop_table('flight_legs')
    op.drop_table('employees')
    op.drop_table('companies_admins')
    op.drop_table('users')
    op.drop_table('lodging_partners')
    op.drop_table('flight_trips')
    op.drop_table('destinations')
    op.drop_table('companies')
    # ### end Alembic commands ###
