"""test

Revision ID: 1593da66c65a
Revises: 7130be121ed0
Create Date: 2021-07-13 16:17:58.721083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1593da66c65a'
down_revision = '7130be121ed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_logs', sa.Column('email_id', sa.String(), nullable=True))
    op.drop_column('email_logs', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_logs', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('email_logs', 'email_id')
    # ### end Alembic commands ###
