"""Add state to RFP table

Revision ID: 15bc5bc50c0f
Revises: f07f50188626
Create Date: 2021-08-04 17:09:36.336715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15bc5bc50c0f'
down_revision = 'f07f50188626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lodging_proposal_requests', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lodging_proposal_requests', 'state')
    # ### end Alembic commands ###
