"""added login token

Revision ID: 2c7f24782261
Revises: c3e30f717c06
Create Date: 2021-03-23 23:37:02.803645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c7f24782261'
down_revision = 'c3e30f717c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_login_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login_token', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_login_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_login_tokens')),
    sa.UniqueConstraint('login_token', name=op.f('uq_users_login_tokens_login_token'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_login_tokens')
    # ### end Alembic commands ###
