"""added created at to login provider

Revision ID: 30b2629da526
Revises: 2c7f24782261
Create Date: 2021-03-23 23:57:39.434874

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '30b2629da526'
down_revision = '2c7f24782261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_login_providers', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE users_login_providers SET created_at = (select now() at time zone 'UTC')")
    op.alter_column('users_login_providers', 'created_at', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_login_providers', 'created_at')
    # ### end Alembic commands ###
