"""init lodging rfp table

Revision ID: 4aab6d7e30c2
Revises: 25ea385abaf7
Create Date: 2021-07-27 02:20:33.537576

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4aab6d7e30c2'
down_revision = '25ea385abaf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lodging_proposal_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_attendees', sa.Integer(), nullable=False),
    sa.Column('flexible_dates', sa.Boolean(), nullable=False),
    sa.Column('occupancy_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meeting_spaces', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('number_nights', sa.Integer(), nullable=True),
    sa.Column('preferred_months', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferred_start_dow', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(NOT flexible_dates) OR (flexible_dates AND number_nights IS NOT NULL)', name=op.f('ck_lodging_proposal_requests_flexible_num_nights_required')),
    sa.CheckConstraint('(NOT flexible_dates) OR (flexible_dates AND preferred_months IS NOT NULL)', name=op.f('ck_lodging_proposal_requests_flexible_months_required')),
    sa.CheckConstraint('(NOT flexible_dates) OR (flexible_dates AND preferred_start_dow IS NOT NULL)', name=op.f('ck_lodging_proposal_requests_flexible_dow_required')),
    sa.CheckConstraint('(flexible_dates) OR (NOT flexible_dates AND end_date IS NOT NULL)', name=op.f('ck_lodging_proposal_requests_exact_end_date_required')),
    sa.CheckConstraint('(flexible_dates) OR (NOT flexible_dates AND start_date IS NOT NULL)', name=op.f('ck_lodging_proposal_requests_exact_start_date_required')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lodging_proposal_requests'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lodging_proposal_requests')
    # ### end Alembic commands ###
