"""Added stripe simple models

Revision ID: 5e64fb05f101
Revises: f5adeb6cf064
Create Date: 2021-04-01 00:17:07.192285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e64fb05f101'
down_revision = 'f5adeb6cf064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_customers',
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_stripe_customers_user_id_users')),
    sa.PrimaryKeyConstraint('customer_id', name=op.f('pk_stripe_customers')),
    sa.UniqueConstraint('user_id', name=op.f('uq_stripe_customers_user_id'))
    )
    op.create_table('stripe_payment_intents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('client_secret', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('REQUIRES_PAYMENT_METHOD', 'REQUIRES_CONFIRMATION', 'REQUIRES_ACTION', 'SUCCEEDED', 'CANCELED', name='stripepaymentintentstatus'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['stripe_customers.customer_id'], name=op.f('fk_stripe_payment_intents_customer_id_stripe_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stripe_payment_intents'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stripe_payment_intents')
    op.drop_table('stripe_customers')
    # ### end Alembic commands ###
