"""add selected proposal to retreat

Revision ID: 5f52b12f75e6
Revises: 67dbe7217bcf
Create Date: 2021-04-27 16:12:03.878179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f52b12f75e6'
down_revision = '67dbe7217bcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retreats', sa.Column('selected_proposal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_retreats_selected_proposal_id_retreats_proposals'), 'retreats', 'retreats_proposals', ['selected_proposal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_retreats_selected_proposal_id_retreats_proposals'), 'retreats', type_='foreignkey')
    op.drop_column('retreats', 'selected_proposal_id')
    # ### end Alembic commands ###
