"""added sales csv related columns to rfp table

Revision ID: 5f7593d0f227
Revises: 53282eab0220
Create Date: 2021-08-10 11:20:02.303384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f7593d0f227'
down_revision = '53282eab0220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lodging_proposal_requests', sa.Column('amount_invoiced', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('lodging_proposal_requests', sa.Column('days_to_pay', sa.Integer(), nullable=True))
    op.add_column('lodging_proposal_requests', sa.Column('employees_paid_for', sa.Integer(), nullable=True))
    op.add_column('lodging_proposal_requests', sa.Column('final_end_date', sa.Date(), nullable=True))
    op.add_column('lodging_proposal_requests', sa.Column('final_location', sa.String(), nullable=True))
    op.add_column('lodging_proposal_requests', sa.Column('final_num_attendees', sa.Integer(), nullable=True))
    op.add_column('lodging_proposal_requests', sa.Column('final_start_date', sa.Date(), nullable=True))
    op.add_column('lodging_proposal_requests', sa.Column('gmv_estimate', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('lodging_proposal_requests', sa.Column('hotel_commision_received_date', sa.Date(), nullable=True))
    op.add_column('lodging_proposal_requests', sa.Column('hotel_commission', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('lodging_proposal_requests', sa.Column('hotel_contract_signed_date', sa.Date(), nullable=True))
    op.add_column('lodging_proposal_requests', sa.Column('hotel_name', sa.String(), nullable=True))
    op.add_column('lodging_proposal_requests', sa.Column('invoice_adjustment', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('lodging_proposal_requests', sa.Column('invoice_paid_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lodging_proposal_requests', sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lodging_proposal_requests', 'total')
    op.drop_column('lodging_proposal_requests', 'invoice_paid_at')
    op.drop_column('lodging_proposal_requests', 'invoice_adjustment')
    op.drop_column('lodging_proposal_requests', 'hotel_name')
    op.drop_column('lodging_proposal_requests', 'hotel_contract_signed_date')
    op.drop_column('lodging_proposal_requests', 'hotel_commission')
    op.drop_column('lodging_proposal_requests', 'hotel_commision_received_date')
    op.drop_column('lodging_proposal_requests', 'gmv_estimate')
    op.drop_column('lodging_proposal_requests', 'final_start_date')
    op.drop_column('lodging_proposal_requests', 'final_num_attendees')
    op.drop_column('lodging_proposal_requests', 'final_location')
    op.drop_column('lodging_proposal_requests', 'final_end_date')
    op.drop_column('lodging_proposal_requests', 'employees_paid_for')
    op.drop_column('lodging_proposal_requests', 'days_to_pay')
    op.drop_column('lodging_proposal_requests', 'amount_invoiced')
    # ### end Alembic commands ###
