"""add foreignkey reference

Revision ID: 6f8d27d162eb
Revises: 0950a8e2a825
Create Date: 2021-06-17 02:54:29.419106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f8d27d162eb'
down_revision = '0950a8e2a825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lodging_proposals', sa.Column('retreat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_lodging_proposals_retreat_id_retreats'), 'lodging_proposals', 'retreats', ['retreat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_lodging_proposals_retreat_id_retreats'), 'lodging_proposals', type_='foreignkey')
    op.drop_column('lodging_proposals', 'retreat_id')
    # ### end Alembic commands ###
