"""test

Revision ID: 7130be121ed0
Revises: 97c27833a997
Create Date: 2021-07-12 21:45:42.887785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7130be121ed0'
down_revision = '97c27833a997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_logs', sa.Column('date_added', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_logs', 'date_added')
    # ### end Alembic commands ###
