"""added flight receipts email logs table

Revision ID: 71b81cf00437
Revises: 6f8d27d162eb
Create Date: 2021-07-14 23:23:47.940982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71b81cf00437'
down_revision = '6f8d27d162eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.String(), nullable=True),
    sa.Column('email_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_logs'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_logs')
    # ### end Alembic commands ###
