"""added retreat filter details

Revision ID: 9d46501beb54
Revises: 5f52b12f75e6
Create Date: 2021-04-28 14:38:21.375772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d46501beb54'
down_revision = '5f52b12f75e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retreats', sa.Column('num_employees', sa.Integer(), nullable=False, server_default="10"))
    op.add_column('retreats', sa.Column('num_nights', sa.Integer(), nullable=False, server_default="4"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('retreats', 'num_nights')
    op.drop_column('retreats', 'num_employees')
    # ### end Alembic commands ###
