"""updated checkout models

Revision ID: a995d780dc1a
Revises: e124f365e90f
Create Date: 2021-04-29 04:08:04.184503

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a995d780dc1a'
down_revision = 'e124f365e90f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkout_orders', sa.Column('customer_id', sa.String(), nullable=True))
    op.create_foreign_key(op.f('fk_checkout_orders_customer_id_stripe_customers'), 'checkout_orders', 'stripe_customers', ['customer_id'], ['customer_id'])
    op.drop_column('checkout_orders', 'name')
    op.drop_column('checkout_orders', 'paid')
    op.drop_column('checkout_orders', 'description')
    op.drop_column('checkout_orders', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkout_orders', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('checkout_orders', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('checkout_orders', sa.Column('paid', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('checkout_orders', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_checkout_orders_customer_id_stripe_customers'), 'checkout_orders', type_='foreignkey')
    op.drop_column('checkout_orders', 'customer_id')
    # ### end Alembic commands ###
