"""added exact_dates column to rfp table

Revision ID: ae8c8657a478
Revises: f07f50188626
Create Date: 2021-08-03 19:51:06.228061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ae8c8657a478'
down_revision = 'f07f50188626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_lodging_proposal_requests_exact_start_date_required'), 'lodging_proposal_requests', type_='check')
    op.drop_constraint(op.f('ck_lodging_proposal_requests_exact_end_date_required'), 'lodging_proposal_requests', type_='check')
    op.add_column('lodging_proposal_requests', sa.Column('exact_dates', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lodging_proposal_requests', 'exact_dates')
    sa.CheckConstraint('(flexible_dates) OR (NOT flexible_dates AND end_date IS NOT NULL)', name=op.f('ck_lodging_proposal_requests_exact_end_date_required')),
    sa.CheckConstraint('(flexible_dates) OR (NOT flexible_dates AND start_date IS NOT NULL)', name=op.f('ck_lodging_proposal_requests_exact_start_date_required')),
    # ### end Alembic commands ###
