"""add created_at column to rfp table

Revision ID: bc5a7a9b0550
Revises: f8d48fa8d420
Create Date: 2021-07-29 04:01:56.119494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc5a7a9b0550'
down_revision = 'f8d48fa8d420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lodging_proposal_requests', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lodging_proposal_requests', 'created_at')
    # ### end Alembic commands ###
