"""add rfp lite response endpoint

Revision ID: c324dbc4a0f8
Revises: decfc637ff32
Create Date: 2021-08-23 10:44:01.212911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c324dbc4a0f8'
down_revision = 'decfc637ff32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfp_lite_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lodging_proposal_request_id', sa.Integer(), nullable=False),
    sa.Column('availability_response', sa.Boolean(), nullable=False),
    sa.Column('hotel_name', sa.String(), nullable=False),
    sa.Column('dates', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lodging_proposal_request_id'], ['lodging_proposal_requests.id'], name=op.f('fk_rfp_lite_responses_lodging_proposal_request_id_lodging_proposal_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rfp_lite_responses'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rfp_lite_responses')
    # ### end Alembic commands ###
