"""added uid column to retreat item

Revision ID: c3e30f717c06
Revises: 22727846837e
Create Date: 2021-03-18 22:09:15.744101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3e30f717c06'
down_revision = '22727846837e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retreats_items', sa.Column('uid', sa.String(), nullable=True))
    op.create_unique_constraint(op.f('uq_retreats_items_uid'), 'retreats_items', ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_retreats_items_uid'), 'retreats_items', type_='unique')
    op.drop_column('retreats_items', 'uid')
    # ### end Alembic commands ###
