"""added employee location models

Revision ID: c5725774a22e
Revises: 30b2629da526
Create Date: 2021-03-26 01:59:09.695462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5725774a22e'
down_revision = '30b2629da526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retreats_employees_locations_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('retreat_id', sa.Integer(), nullable=True),
    sa.Column('extra_info', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['retreat_id'], ['retreats.id'], name=op.f('fk_retreats_employees_locations_submissions_retreat_id_retreats')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retreats_employees_locations_submissions'))
    )
    op.create_table('retreats_employees_locations_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=False),
    sa.Column('google_place_id', sa.String(), nullable=False),
    sa.Column('main_text', sa.String(), nullable=False),
    sa.Column('secondary_text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['retreats_employees_locations_submissions.id'], name=op.f('fk_retreats_employees_locations_items_submission_id_retreats_employees_locations_submissions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retreats_employees_locations_items'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retreats_employees_locations_items')
    op.drop_table('retreats_employees_locations_submissions')
    # ### end Alembic commands ###
