"""add calendly info to rfp table

Revision ID: decfc637ff32
Revises: 5f7593d0f227
Create Date: 2021-08-19 00:58:49.229214

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'decfc637ff32'
down_revision = '5f7593d0f227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lodging_proposal_requests', sa.Column('intake_call_calendly_event', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lodging_proposal_requests', 'intake_call_calendly_event')
    # ### end Alembic commands ###
