"""added flok note field to retreat

Revision ID: e124f365e90f
Revises: 9d46501beb54
Create Date: 2021-04-28 17:08:47.699218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e124f365e90f'
down_revision = '9d46501beb54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retreats', sa.Column('flok_note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('retreats', 'flok_note')
    # ### end Alembic commands ###
