"""added initial proposals table

Revision ID: f5adeb6cf064
Revises: c5725774a22e
Create Date: 2021-03-26 21:41:31.189127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5adeb6cf064'
down_revision = 'c5725774a22e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retreats_initial_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('retreat_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('dates_range', sa.String(), nullable=False),
    sa.Column('num_nights_estimate', sa.String(), nullable=False),
    sa.Column('flight_time_avg', sa.String(), nullable=False),
    sa.Column('weather_prediction', sa.String(), nullable=False),
    sa.Column('lodging_estimate', sa.String(), nullable=False),
    sa.Column('flights_estimate', sa.String(), nullable=False),
    sa.Column('transportation_estimate', sa.String(), nullable=True),
    sa.Column('misc_estimate', sa.String(), nullable=True),
    sa.Column('total_estimate', sa.String(), nullable=True),
    sa.Column('extra_info', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['retreat_id'], ['retreats.id'], name=op.f('fk_retreats_initial_proposals_retreat_id_retreats')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retreats_initial_proposals'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retreats_initial_proposals')
    # ### end Alembic commands ###
