"""added email & attendees range to rfp table

Revision ID: f8d48fa8d420
Revises: 3048cc1a31ca
Create Date: 2021-07-28 04:44:26.907013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8d48fa8d420'
down_revision = '3048cc1a31ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lodging_proposal_requests', sa.Column('email', sa.String(), nullable=False))
    op.add_column('lodging_proposal_requests', sa.Column('number_attendees_range_lower', sa.Integer(), nullable=True))
    op.add_column('lodging_proposal_requests', sa.Column('number_attendees_range_upper', sa.Integer(), nullable=True))
    op.alter_column('lodging_proposal_requests', 'number_attendees',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lodging_proposal_requests', 'number_attendees',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('lodging_proposal_requests', 'number_attendees_range_upper')
    op.drop_column('lodging_proposal_requests', 'number_attendees_range_lower')
    op.drop_column('lodging_proposal_requests', 'email')
    # ### end Alembic commands ###
